### PR TITLE
LandingUpdate

### PR DESCRIPTION
**Pull request by SuyashRajput**
Here the new landing page

### CODE REVIEW

**Comment by arcVaishali** [comment]
The Hero Text is missing, add lorem ipsums.

**Comment by arcVaishali** [comment]
Also we saw you have added Bootstrap, just wanted to know will this not cause namespace pollution, as for styling Tailwind CSS has been already added.

**Comment by SuyashRajput** [comment]
Where do you want me to add the hero text.
As for the bootstrap it does not causes any conflicts if you want I can remove it

**Comment by SuyashRajput** [comment]
image
If you are talking about this text I can add this on the top and continue with the other design which I have made

**Comment by arcVaishali** [comment]
Modify first label, second label...etc that you have put on image slider in the hero section. Make it a bit larger, similar to the design that I have provided from webflow. And yes, also add two **get started** buttons below first label, second label....

**Comment by arcVaishali** [comment]
I will send you screenshot

**Comment by SuyashRajput** [comment]
ok how about this 
I can make a new section of relief connect that you have on the vercel deploy 
and then continue with the image slider ( and I will modify it like the webflow design )

**Comment by SuyashRajput** [comment]
image

**Comment by arcVaishali** [comment]
Yeah that works!

**Comment by SuyashRajput** [comment]
You can check the code now
PS. Removed bootstrap :)

**Pull request merged**
