### PR TITLE
Mobile responsive

### PR DESCRIPTION
**Pull request by priyanshtiwari001**
#13 
Hi @arcVaishali , Kindly review and changes.

### CODE REVIEW

**Comment by priyanshtiwari001** [comment]
Hi @arcVaishali , can you please review?

**Comment by arcVaishali** [comment]
Yes, some of the pages are not responsive yet for all screen sizes, pls check again. Check App.js and make all pages responsive and for the navbar, for smaller window sizes implement something like hamburger menu.

**Comment by priyanshtiwari001** [comment]
Hi @arcVaishali, I am sorry to say but first of all , you didn't clarifying properly what   you really want and how to want?  You are just saying make responsive. Previous I did changes, after that you were telling me that our landing page is changed. That's not good. If you want then you can merge these changes otherwise unassign to me. Thank you!!

**Comment by arcVaishali** [comment]
Sorry for delayed response but do check the preview of your branch it is not even responsive for large screen sizes. No worries you can work on some other issue.

**Pull request closed without merging**
